# Generated by Django 5.2.1 on 2025-05-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_cartitem_product_alter_cartitem_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='Not Provided'),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='Not Provided', max_length=15),
        ),
    ]
